nick = "korasho"
alt = "korash__"
username = "korasho"
realname = "korasho"

[[servers]]
host = "chat.freenode.net"
port = 6697
secure = true
nick = "korasho-bot"
alt = "korasho_bot"
channels = [ "#korasho", "#korashobot" ]

[[servers]]
host = "irc.mozilla.org"
port = 6667
channels = [ "#korasho", "#korashobot", "#rustbot" ]
