[package]
name = "korasho"
version = "0.1.0"
authors = ["Bjorn Tipling <bjorn@ambientchill.com>"]

[[bin]]
name = "korasho"
path = "src/main.rs"

[dependencies]
openssl = "0.7.4"
toml = "0.1.25"
time = "0.1.34"
